### ISSUE TITLE
Can we rename the repo to vscode-gwion ?

### ISSUE THREAD

**Issue by forrcaho** [Gwion/vscode-extension#2]
I know this is under the Gwion project in Github, but that context is not always around (e.g. when someone checks out just this repo). A common convention, which I followed on my ChucK extension, is to name the repo vscode-languagename.

I don't know if it's possible to rename an existing repo on Github, but I think it would be good if we could.

**Comment by benrogmans** [comment]
It’s done, thanks for the suggestion!
